services:
  nestjs:
    build:
      context: docker/backend
      dockerfile: Dockerfile
    container_name: nestjs
    volumes:
      - "./backend/:/var/www/html"
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
  postgres:
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: task-tracker
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - ./backend/var/db-data:/var/lib/postgresql/data:rw
